workflows:
  build-android:
    name: Android Build (Free Tier)
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 18
    scripts:
      - npm install
      - npx expo install
      - npx eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
