workflows:
  build-android:
    name: Android APK & AAB Build (Free Plan)
    instance_type: linux
    environment:
      node: 18
      vars:
        EXPO_TOKEN: Encrypted_Expo_Token  # Replace or set via Codemagic UI
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm install -g expo-cli eas-cli
      - name: Expo Login
        script: |
          eas whoami || eas login --token $EXPO_TOKEN
      - name: Build APK
        script: |
          eas build --platform android --profile preview --non-interactive --output=apk
      - name: Build AAB
        script: |
          eas build --platform android --profile preview --non-interactive --output=aab
    artifacts:
      - '**/*.apk'
      - '**/*.aab'
