workflows:
  android-build:
    name: Android APK & AAB Build
    instance_type: mac_mini  # <- FREE tier compatible instance
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 18
    scripts:
      - npm ci
      - npx expo install
      - npx eas build --platform android --non-interactive
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
