name: EAS Build CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: EAS Build (Android - APK & AAB)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        run: npm install -g expo-cli eas-cli

      - name: Authenticate with Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build AAB
        run: eas build --platform android --profile preview-aab --non-interactive

      - name: Build APK
        run: eas build --platform android --profile preview-apk --non-interactive

      - name: Output latest Android builds
        run: |
          echo "Fetching latest Android build URLs..."
          eas build:list --platform android --limit 2 --json > builds.json
          cat builds.json
          echo "🔗 AAB URL: $(cat builds.json | jq -r '.[0].artifacts.buildUrl')"
          echo "🔗 APK URL: $(cat builds.json | jq -r '.[1].artifacts.buildUrl')"
